### ISSUE TITLE
Backup on interval

### ISSUE THREAD

**Issue by mswdev** [cgcel/obsidian-local-backup#1]
Hi @cgcel,

This tool is fantastic for pairing with Google Drive/File Stream, iCloud, Dropbox, etc without having to setup complex syncers like other plugins.

However, I wish it had a backup on interval function rather than just a backup on startup. Is this something you'd be interested in adding?

For example, backing up the vault every 10 minutes while deleting previous backups to save on storage.

Thanks!
Matt

**Comment by cgcel** [comment]
Looks great, I will add this feature to the plugin.

**Comment by mswdev** [comment]
Thank you for the quick reply! I look forward to it!

[data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACwAAAAAAQABAAACAkQBADs=3D]

**Comment by cgcel** [comment]
Hi, 0.0.6 released just now, have a try on interval backup, I suggest to set a normal interval (like >=10min) because this plugin costs cpu io resources.
