### ISSUE TITLE
[FEAT] Support for file name with custom date

### ISSUE THREAD

**Issue by trey-wallis** [cgcel/obsidian-local-backup#10]
## Problem
I would like a custom date format to appear at the end of the file name e.g. `my-backup-2023_10_24-12_00`

## Solution
I think some form of parsing for the `%` symbol would be good.

For example, in Bash you might have
```bash
printf -v date '%(%Y-%m-%d %H:%M:%S)T\n' -1 
```

Where %Y represents year,
%m represents month,
etc

I think all of the those in the string would be good to implement
- `%Y` - year
- `%m` - month
- `%d` - day
- `%H` - hour
- `%M` - minute
- `%S` - second

If you have another format that you would prefer that would work as well

**Comment by trey-wallis** [comment]
@cgcel Is it okay if I make a pull request to implement this?

**Comment by cgcel** [comment]
> @cgcel I would be willing to implement this shortly, if you're open to collaborations.

Yes of course🎉

**Comment by cgcel** [comment]
Your code has been merged, and I updated the code of autoDelete, thanks for your contribution!
