### ISSUE TITLE
"Failed to create vault backup" error

### ISSUE THREAD

**Issue by Marco-Mindstone** [cgcel/obsidian-local-backup#12]
After last update I get this error:

![image](https://github.com/cgcel/obsidian-local-backup/assets/112725579/146e4e0c-3dd1-4b33-96d1-e20b3776baf0)

**Comment by cgcel** [comment]
Hi, could you share your settings of the plugin?

**Comment by Marco-Mindstone** [comment]
Hi, sure. Here they are:

<img width="817" alt="image" src="https://github.com/cgcel/obsidian-local-backup/assets/112725579/74df972b-7213-47c8-8758-fe448f3ed734">

Thank you for the support

**Comment by cgcel** [comment]
Hi Marco, sorry for the late replying, I can't reproduce your error, maybe my vault is too small (My main vault is about 7MB and my test vault is about 22MB), what size is yours?

**Comment by Marco-Mindstone** [comment]
Hi, it's 2.46 GB.

**Comment by cgcel** [comment]
Thanks for your replying! I'm going to change the way generating the zip file from open directory directly to create an io stream and write into zip file, hope this can help😊

**Comment by Marco-Mindstone** [comment]
Sounds good! I will test it and let you know as soon as you release the update 😉

**Comment by cgcel** [comment]
Hi, 0.0.9 released, you can try the experimental feature, `Backup by 7-Zip`, if toggled, backups will be created by calling 7zip, and obsidian won't stuck any more if everything goes well.

**Comment by Marco-Mindstone** [comment]
Perfect! It works. Thank you 😉
