### ISSUE TITLE
[BUG] Save path isn't updating

### ISSUE THREAD

**Issue by trey-wallis** [cgcel/obsidian-local-backup#14]
My save path isn't updating even though I have changed it. I looked in the `data.json` file created by the plugin settings and it looks like there's a bunch of duplicates.

I have it set to `backups` but it still saving in `second_brain-backups`

I had updated the config and did press "Apply && Save"

<img width="683" alt="image" src="https://github.com/cgcel/obsidian-local-backup/assets/40307803/cbc0e8aa-fe9d-411d-9d21-e5604c476bd6">

<img width="823" alt="image" src="https://github.com/cgcel/obsidian-local-backup/assets/40307803/74b25c63-6b53-490c-91e0-ee1f3d757c72">

**Comment by trey-wallis** [comment]
Here is the raw text if you want to try to use it

```json
{
  "versionValue": "0.1.0",
  "startupBackupStatus": false,
  "lifecycleValue": "7",
  "backupsPerDayValue": "1",
  "winSavePathValue": "",
  "unixSavePathValue": "/Users/trey/Desktop/backups",
  "fileNameFormatValue": "second_brain-backup-%Y_%m_%d-%H_%M_%S",
  "intervalBackupStatus": false,
  "backupFrequencyValue": "10",
  "callingArchiverStatus": false,
  "archiverTypeValue": "sevenZip",
  "archiverPathValue": "",
  "startupSetting": false,
  "lifecycleSetting": "7",
  "backupsPerDaySetting": "1",
  "winSavePathSetting": "/Users/trey/Desktop/second_brain-backups",
  "unixSavePathSetting": "/Users/trey/Desktop/second_brain-backups",
  "customizeNameSetting": "second_brain-backup-%Y_%m_%d-%H_%M_%S",
  "intervalToggleSetting": true,
  "intervalValueSetting": "20",
  "sevenZipBackupToggleSetting": false,
  "sevenZipPathSetting": "",
  "savePathSetting": "/Users/trey/Desktop/second_brain-backups"
}
```

**Comment by trey-wallis** [comment]
In other Obsidian plugins, they don't use an "Apply && Save" button. The text is automatically saved upon any change to the text input. The `Restore defaults` button makes sense to me.

Would it be possible to remove the "Apply && Save" button and just save any changes?

**Comment by cgcel** [comment]
Yes you are right , the button will be removed in the next version.

**Comment by trey-wallis** [comment]
Sounds good. Thank you for the great plugin! It has given me more ease of mind with my second brain. I love the configuration options from inside Obsidian.

**Comment by cgcel** [comment]
Hi Trey, this bug has fixed and the `Apply && Save` button has been removed.
