### ISSUE TITLE
[BUG] For some reason the backed up zip can't be found

### ISSUE THREAD

**Issue by Hexara7777** [cgcel/obsidian-local-backup#15]
Hi there, as the title suggests, for some reason the plugin shows me that "File X was created in X directory" but I can't find those created backups in that directory, even restoring it to default settings won't solve this problem.

This bug applies to backup on start, backup on interval or backup command (command palette).

**Comment by cgcel** [comment]
Hi, could you share the console log by pressing "ctrl + shift + i"?

**Comment by Hexara7777** [comment]
server started at http://localhost:3000
plugin:table-editor-obsidian:28663 loading markdown-table-editor plugin
plugin:editing-toolbar:9 cMenuToolbar v2.3.1 loaded
plugin:obsidian-qrcode-plugin:2957 loading plugin
plugin:find-unlinked-files:488 loading Find orphaned files and broken links plugin
plugin:obsidian-outliner:3317 Loading obsidian-outliner
plugin:url-into-selection:690 loading url-into-selection
plugin:quickadd:19507 Loading QuickAdd
plugin:quickadd:17507 QuickAdd: (LOG) No migrations to run.
plugin:obsidian-sortable:180 Sortable: loading plugin...
plugin:obsidian-sortable:183 Sortable: loaded plugin.
plugin:obsidian-vault-statistics-plugin:691 Loading vault-statistics Plugin
plugin:obsidian-paste-image-rename:465 Plugin loading: obsidian-paste-image-rename 1.6.1 BUILD_ENV=production
plugin:link-favicon:9 enabling plugin: link favicons
plugin:local-backup:5004 Run deleteBackupsByLifeCycle
plugin:local-backup:5041 Run deletePerDayBackups
plugin:local-backup:5079 Backup removed by deletePerDayBackups: D:\Laptop\Backups\Obsidian\Obsidian Vault V3-Backup-2023_11_13-03_34_47.zip
plugin:link-favicon:7 # 
plugin:link-favicon:7 Goals
plugin:link-favicon:7 1. 
plugin:link-favicon:7 # 
plugin:link-favicon:7 Fields
plugin:link-favicon:7 1. 
plugin:link-favicon:7 Nutrition 💪
plugin:link-favicon:7 2. 
plugin:link-favicon:7 Own a pharmacy 🏥
plugin:link-favicon:7 3. 
plugin:link-favicon:7 Make apps and websites 📱
plugin:link-favicon:7 # 
plugin:link-favicon:7 Red flags
plugin:link-favicon:7 1. 
plugin:link-favicon:7 Religion doubt ⚠️
plugin:link-favicon:7 2. 
plugin:link-favicon:7 Nail biting is extreme 👋
plugin:link-favicon:7 3. 
plugin:link-favicon:7 Forgetting 😵‍💫
plugin:link-favicon:7 4. 
plugin:link-favicon:7 Feeling sleepy 😴
plugin:link-favicon:7 **
plugin:link-favicon:7 dasdasd
plugin:link-favicon:7 **
plugin:obsidian-excalidraw-plugin:79 Initialized Excalidraw Image Cache
plugin:obsidian-vault-statistics-plugin:464 Excalidraw/Drawing 2023-11-11 17.23.24.excalidraw.md: no tokenizer, section.type=comment
plugin:obsidian-vault-statistics-plugin:464 Excalidraw/Journals.md: no tokenizer, section.type=comment

**Comment by cgcel** [comment]
Can you share the log after running local bakcup command? I couldn't find the log about backing up. And which version are you using?

**Comment by Hexara7777** [comment]
This log is right after the failed backup. Version 1.4.16 for Obsidian and version 0.1.1 for the plugin.

**Comment by cgcel** [comment]
Maybe this issue could be fixed by deleting the `data.json`, according to your logs, the path to it might be: `D:\Laptop\Backups\Obsidian\{Your Vault}\.obsidian\plugins\obsidian-local-backup\data,json`, after delete it , restart Obsidian and see if this bug fixed, and share the content of `data.json` if possible, thanks!

**Comment by Hexara7777** [comment]
I tried all of that and it didn't work, here is the newly created data.json contents:
{
  "versionValue": "0.1.1",
  "startupBackupStatus": true,
  "lifecycleValue": "0",
  "backupsPerDayValue": "0",
  "winSavePathValue": "D:\\Laptop",
  "unixSavePathValue": "D:\\Laptop",
  "fileNameFormatValue": "Obsidian Vault V3-Backup-%Y_%m_%d-%H_%M_%S",
  "intervalBackupStatus": false,
  "backupFrequencyValue": "10",
  "callingArchiverStatus": false,
  "archiverTypeValue": "sevenZip",
  "archiveFileTypeValue": "zip",
  "archiverPathValue": ""
}

**Comment by cgcel** [comment]
Thanks for your report, I reproduced this bug, will fix at version 0.1.3

**Comment by Hexara7777** [comment]
You're welcome! Glad it will be fixed that fast :D
