### ISSUE TITLE
Range Error: Array buffer allocation failed

### ISSUE THREAD

**Issue by Marco-Mindstone** [cgcel/obsidian-local-backup#16]
Hi, something went wrong after the last patch:

![image](https://github.com/cgcel/obsidian-local-backup/assets/112725579/15ffa0f1-6188-4e67-a7fe-8250eea401e2)

**Comment by cgcel** [comment]
Have you turned on the backup by calling external file archiver?

**Comment by Marco-Mindstone** [comment]
I'm blind...
Thank you!

**Comment by cgcel** [comment]
Glad to help you😉
