### ISSUE TITLE
failed to create vault backup: rangeerror: array buffer allocation failed

### ISSUE THREAD

**Issue by ghost** [cgcel/obsidian-local-backup#17]
failed to create vault backup: rangeerror: array buffer allocation failed, why this error occured?

**Comment by cgcel** [comment]
Pls share the content of `data.json` in `<Your Vault>/.obsidian/plugins/obsidian-local-backup`, if your vault is in a large size, I suggest you setup the file archiver settings, the archive file will created by calling 7-Zip:

![image](https://github.com/cgcel/obsidian-local-backup/assets/23419678/2c9bafbb-cc13-4a03-b933-3074299af298)

**Comment by kennygokh** [comment]
Hi @cgcel , I encountered same issue. I am using macOS, what should I do?

**Comment by cgcel** [comment]
> Hi @cgcel , I encountered same issue. I am using macOS, what should I do? 

Install 7-zip and fill the file archiver path (Unix), then you can create an archive file by calling 7-zip, and your issue may be resolved.

**Comment by kennygokh** [comment]
Thanks. Got it working now though I downloaded using sevenzip install via brew. Found [brew install sevenzip will install the package still maintained by the original developers](https://superuser.com/questions/548349/how-can-i-install-7zip-so-i-can-run-it-from-terminal-on-os-x) that explain that the 7zz will maintain by the original developers.
