### ISSUE TITLE
Failed to update

### ISSUE THREAD

**Issue by Marco-Mindstone** [cgcel/obsidian-local-backup#2]
Hi, Obsidian is telling me that there is an update for the plugin but when I try to upload it I encounter an error.

<img width="272" alt="image" src="https://github.com/cgcel/obsidian-local-backup/assets/112725579/055368fa-758c-4feb-aad5-3e92f02a3d03">

**Comment by cgcel** [comment]
I updated the version string yesterday and I haven't published the release yet, I'll fix it, thank you for announcing me.

**Comment by cgcel** [comment]
0.0.6 released. 😊
