### ISSUE TITLE
Obsidian lags on startup

### ISSUE THREAD

**Issue by jamie9090** [cgcel/obsidian-local-backup#21]
With backups set to run on startup, Obsidian hangs on "Loading plugins". For now, I've switched it off and using 60 minute intervals.

Is it possible to have the Obsidian backup process a little after launching, this way the startup experience is fast, but backup still occurs?

**Comment by cgcel** [comment]
Hi, thank you for using, your suggestion is cool and I will add it in the future version. For now my suggestion is:

If your Obsidian Vault is in a large size, setup `File Archiver Settings (Optional)` in Local Backup setting page, after that Obsidian could create backups by calling external file archiver without any laggings.

**Comment by jamie9090** [comment]
Awesome, thank you.
