### ISSUE TITLE
Error message in developer console: Failed to create file by 7-Zip: Error: Command failed: 

### ISSUE THREAD

**Issue by merlinuwe** [cgcel/obsidian-local-backup#22]
Thanks for your great plugin.

When I look into the developer console, I see this error-message:

![image](https://github.com/cgcel/obsidian-local-backup/assets/4138869/f46ff3d9-2ef7-4afb-9872-08ca661f92e4)

I guess, it has something to do with ending and restarting Obsidian.

(I use the latest release of Obsidian and your plugin.)

Is there something I can adjust in the settings to prevent this message?

**Comment by cgcel** [comment]
Hello, according to your screenshot, it looks like the plugin "codeblock-customizer" is editing it's data.json, so 7-Zip couldn't create an archive file.

**Comment by merlinuwe** [comment]
Do you think it makes sense to retry the backup due to such access at a later point in the backup history (before the backup fails)?

**Comment by cgcel** [comment]
I think it's possible to add a customized retry count (e.g. up to 3 retries after backup failed).

**Comment by cgcel** [comment]
The latest version 0.1.6 released and adds retry settings, hope this helps.

**Comment by merlinuwe** [comment]
Thank you very much, I'll test it with these settings:

<img width="445" alt="image" src="https://github.com/cgcel/obsidian-local-backup/assets/4138869/39436a60-e0f1-4a21-8757-4eab7fd95fb5">
