### ISSUE TITLE
Allow compressed packets backed up at multiple times to coexist

### ISSUE THREAD

**Issue by Xieleilab** [cgcel/obsidian-local-backup#23]
When using the backup function now, the compressed file created at the current time will overwrite the previously backed up compressed file. Can you cancel the overwrite? Or allow users to customize

**Comment by cgcel** [comment]
Hi, which version of plugin are you using? Upgrade to the latest version and you could set up the filename at setting page by using Y(year) M(month) d(day) H(hour) m(minute) s(second)

**Comment by Xieleilab** [comment]
the version used is 0.1.6,  but even after i set up the filename by adding Y(year) M(month) d(day) , Backup files generated in the past will still be overwritten by newly generated backup files.

**Comment by cgcel** [comment]
Please share your Local Backup settings :)

Here is an example: `TestVault-Backup-%Y_%m_%d-%H_%M_%S`, and the backup files like:

![image](https://github.com/cgcel/obsidian-local-backup/assets/23419678/7e364fab-6c05-4f02-9299-b94116f59c6e)

**Comment by Xieleilab** [comment]
filename: 我的obsidian笔记-Backup-%Y_%m_%d 
![image](https://github.com/cgcel/obsidian-local-backup/assets/78771561/9df75850-584a-4d3f-9c2c-8d06d9c79db6)

 the backup files:
![image](https://github.com/cgcel/obsidian-local-backup/assets/78771561/175b6229-f8aa-440c-9bb5-2ff1869a53da)

**Comment by cgcel** [comment]
It will cover the previous file if you name it like this, the feature you want doesn't exist yet. If you want to keep all the files, I suggest you to setup the Filename format like the example above 😀
