### ISSUE TITLE
[Feature Request] Handle user created backup differently 

### ISSUE THREAD

**Issue by greenconda** [cgcel/obsidian-local-backup#24]
Add an option to handle user created backup differently such that, it can be backed up by different name, than default. For example if I am taking a backup before installing a specific plugin. I can name it accordingly while taking backup

An option to keep user generated backups forever and not remove them as per the limits defined in the options

**Comment by cgcel** [comment]
Thank you for your advice, I will work on this feature.

**Comment by cgcel** [comment]
Now you can create a specific backup file in version 0.1.7, which won't delete by the plugin, just type: ctrl + p, local backup and find this command.

**Comment by greenconda** [comment]
Wow thank you for adding this so quickly 💟
