### ISSUE TITLE
Unclear: Backup history length (days)

### ISSUE THREAD

**Issue by mdelgadoschwartz** [cgcel/obsidian-local-backup#27]
Hi, 

It is not clear how the backup's are being made. There is a switch that allows one to specify the days a backup should be retained... but does it do so even when there is only one backup remaining?

For example, when in one day three backups are made, but then Obsidian is not used for a week, at the start up of Obsidian a week later, are the three backups deleted before or after a new "fresh" backup has been made? 

Thanks in advance for clarifying!

**Comment by cgcel** [comment]
> It is not clear how the backup's are being made. There is a switch that allows one to specify the days a backup should be retained... but does it do so even when there is only one backup remaining?

Up to version 0.1.7, yes it does.

> For example, when in one day three backups are made, but then Obsidian is not used for a week, at the start up of Obsidian a week later, are the three backups deleted before or after a new "fresh" backup has been made?

The backups will be deleted after a new backup created.

**Comment by mdelgadoschwartz** [comment]
Ah, perfect. Thanks for clarifying!
