### ISSUE TITLE
Customize the backup name

### ISSUE THREAD

**Issue by trey-wallis** [cgcel/obsidian-local-backup#3]
I had made myself a little script with cron jobs for local backups, but I love the idea of having an Obsidian plugin to do this instead.

## Problem
I would like to be able to customize the backup name

## Solution
A setting where you could specify the file name including the date format.

**Comment by cgcel** [comment]
Yes of course, this feature will be added in the coming version. Thank you for your suggestions!

**Comment by cgcel** [comment]
0.0.7 released, add zip name customization.
