### ISSUE TITLE
Feature request: disable backup notifications

### ISSUE THREAD

**Issue by hmijail** [cgcel/obsidian-local-backup#34]
When periodic backups are enabled, the periodic notification is distracting. And they happen even when the vault is unchanged.

It would be great to be able to disable notifications, or only show them when something goes wrong.

The options pane could show when was the last time the backup ran.

**Comment by lukiwieser** [comment]
Hi, love your plugin!

I would also strongly appreciate a feature to simply hide the notifications.

**Comment by cgcel** [comment]
@hmijail @lukiwieser Thank you for your advice, sorry for late replying.

**Comment by sudonem** [comment]
This issue can probably be closed given that the current iteration of the plugin includes a toggle to show/hide notifications.

**Comment by cgcel** [comment]
> This issue can probably be closed given that the current iteration of the plugin includes a toggle to show/hide notifications.
