### ISSUE TITLE
The UI thread is blocked when the backup occurs

### ISSUE THREAD

**Issue by trey-wallis** [cgcel/obsidian-local-backup#4]
## Problem
Whenever a backup occurs, the UI thread is blocked. This makes the application freeze until the backup is done.

## Solution
Run the backup on another thread.

**Comment by cgcel** [comment]
Yes, this is a known issue, I'll try to fix it.

**Comment by cgcel** [comment]
I'm afraid I can't run the backup on another thread, obsidian throws exception when I called workder_thread: 

```
Error: The V8 platform used by this instance of Node does not support creating Workers.
```

So this issue would be closed.
