### ISSUE TITLE
Not Backing up after 0.1.8 update

### ISSUE THREAD

**Issue by shallotx** [cgcel/obsidian-local-backup#46]
I am in Obsidian v1.7.4.  Local backups now appear to be empty...

![2024-10-10_16-18](https://github.com/user-attachments/assets/fe535b9b-ade9-4534-b842-8e8bdb1aacf9)

**Comment by cgcel** [comment]
Backup . obsidian/plugins/local-backup/data.json, and reinstall the plugin.

**Comment by shallotx** [comment]
Thank you, that fixed it!
