### ISSUE TITLE
Plugin tab is duplicated when "Apply settings" is pressed

### ISSUE THREAD

**Issue by trey-wallis** [cgcel/obsidian-local-backup#5]
## Problem
When I click "Apply Settings" on desktop, another tab is produced in the plugin list for some reason
<img width="228" alt="image" src="https://github.com/cgcel/obsidian-local-backup/assets/40307803/81c43a70-e24e-44f6-a0d1-8b32b629f583">

## Solution
I am not sure what is causing this.

EDIT: it seem like it is `await this.plugin.onload(); ` that is being called on the button click. I don't think this plugin is meant to be called like this.

**Comment by cgcel** [comment]
Thank you for using this plugin, and thanks for the advice, I will take a look to this issue.

**Comment by cgcel** [comment]
The bug fixed in 0.0.7.
