### ISSUE TITLE
Implement MacOS/UNIX Filesystem support

### ISSUE THREAD

**Issue by mswdev** [cgcel/obsidian-local-backup#7]
Hi,

Could you please implement support for MacOS filesystems?

Right now you can only set one output path. On my Windows 10 machine I have set a custom output path, but when the plugin and configuration sync to my MacOS machine the plugin does not work as the file output path is not the same structure since MacOS uses a UNIX filesystem structure.

A solution would be to convert the user inputted output path to the operating system file path structure.

Thanks!
Matt

**Comment by cgcel** [comment]
I think it is a great idea! Will try to add it in the coming version😀

**Comment by cgcel** [comment]
This feature is included by 0.0.8, so I close this issue. 😀
