### ISSUE TITLE
[BUG]: Error message appears when there is no value for the backup lifecycle input

### ISSUE THREAD

**Issue by trey-wallis** [cgcel/obsidian-local-backup#8]
## Problem
When I erase all the text in the backup lifecycle input, I get a notice message.

<img width="303" alt="image" src="https://github.com/cgcel/obsidian-local-backup/assets/40307803/f4ef6ec9-b2fe-4a9f-bc0b-2e8b0052d388">

## Expected behavior
There should be no notice until I click "Apply settings"

## Steps to reproduce
1. Click on the "Backup Lifecycle" input in the settings modal to focus it
2. Press backspace until there are no characters
3. See message

**Comment by cgcel** [comment]
Will be fixed in the next version, thanks for your testing👍

**Comment by cgcel** [comment]
The bug has been fixed on 0.0.8, pls upgrade it.
