### ISSUE TITLE
[REFACTOR] Confusing naming in English

### ISSUE THREAD

**Issue by trey-wallis** [cgcel/obsidian-local-backup#9]
## Problem
Some of the titles and descriptions do not make sense to me as a native English speaker

<img width="780" alt="image" src="https://github.com/cgcel/obsidian-local-backup/assets/40307803/007fbf96-f9e9-4b26-b341-2666e9d40b86">

<img width="783" alt="image" src="https://github.com/cgcel/obsidian-local-backup/assets/40307803/c410de16-313e-4d43-9444-536fc09aaad0">

<img width="815" alt="image" src="https://github.com/cgcel/obsidian-local-backup/assets/40307803/63601136-68a6-4055-9425-d632facbe3c4">

<img width="804" alt="image" src="https://github.com/cgcel/obsidian-local-backup/assets/40307803/6adcddde-af00-46c3-b0d6-c2959fee6519">

## Suggestions
- "Backup history length" - "Specify the number of days backups should be retained"
- "File name" - "Name of the backup ZIP file"
- "Interval backups" - Enable to create backups at regular intervals
- "Backup frequency" - Set the frequency of backups in minutes

**Comment by cgcel** [comment]
Thank you for providing these translations🤝🤝

**Comment by cgcel** [comment]
Updated in main branch, this issue will be closed. 🤝
